name: 微信读书同步到飞书多维表格

on:
  # 每天北京时间早上8点执行（UTC时间0点）
  schedule:
    - cron: '0 0 * * *'
  # 支持手动触发
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 创建环境变量文件
      run: |
        echo "BITABLE_URL=${{ secrets.BITABLE_URL }}" >> .env
        echo "PERSONAL_BASE_TOKEN=${{ secrets.PERSONAL_BASE_TOKEN }}" >> .env
        echo "WEREAD_COOKIE=${{ secrets.WEREAD_COOKIE }}" >> .env
        
    - name: 运行同步脚本
      run: npx ts-node src/scripts/sync-all-books.ts
      
    - name: 上传同步报告
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-report
        path: sync-report.json
        retention-days: 7